modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/novumscientiateam/NovumScientia/issues"
[[mods]]
modId="novumscientia"
version="${file.jarVersion}"
displayName="Novum Scientia"
authors="TheEmosewaPixel, Bartz24, MrBysco, gerb82, cipherzerox"
description="A large scale tech mod for 1.14+ with the goal of large scale automation"
[[dependencies.novumscientia]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.novumscientia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.novumscientia]]
    modId="pixellib"
    mandatory=true
    versionRange="[1.0.6,)"
    ordering="NONE"
    side="BOTH"